apiVersion: apps/v1
kind: Deployment
metadata:
  name: sps-starters-2024-ducks
  labels:
    app: ducks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ducks
  template:
    metadata:
      labels:
        app: ducks
    spec:
      containers:
      - name: ducks
        image: spscontainerregistryae.azurecr.io/ducks/backend:46d0d96126ce47fdf7d766d4ad7d74ba7b63c647
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "production"
